import { AlertTriangle, Clock, Minus, TrendingDown, TrendingUp, ZapOff } from "lucide-react";
import { z } from "zod";

const reviewSchema = z.object({
  id: z.string(),
  title: z.string(),
  type: z.string(),
  label: z.string(),
  confidence: z.string(),
  verdict: z.string(),
});

export type Review = z.infer<typeof reviewSchema>;

const reviewsData = [
  { id: "FND-0001", title: "Job 7d47fa3f held 8 GPUs idle for 23.1h while 31 jobs queued", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0002", title: "Queue wait 1397min with 31 idle jobs blocking node 5082ec7f", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0003", title: "Job 90362eef held 8 GPUs at 0% utilization for 8h", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0004", title: "Queue wait 1051min — 38 running jobs held unused capacity", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0005", title: "Job 675b04cc allocated 8 A100s but peak utilization was 4%", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0006", title: "Queue wait 947min — blocker job 824986e4 held 8 idle GPUs", type: "queue_inefficiency", label: "queue", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0007", title: "Job 6cb3f43b held full node 8xA100 idle for 9h straight", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0008", title: "Fragmentation: 3 jobs each using 2 GPUs across 3 nodes instead of 1", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0009", title: "Job d5c070ae queue wait 720min — 36 blockers with idle capacity", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0010", title: "Job d4dabaf9 waited 688min — 17 idle jobs at submit time", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0011", title: "Job 185b4ed3 held 8 GPUs with 0 SM utilization for full duration", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0012", title: "Job 618b9d91 queue wait 1341min — pre-emption would have freed 8 GPUs", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0013", title: "Job 29de149a allocated 8 A100-80GB, mean util across all GPUs 0%", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0014", title: "Node b86cd057 entirely idle for 6.2h while queue depth was 12", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0015", title: "Job 42a29003 repeatedly appeared as blocker in 9 queue findings", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0016", title: "Fragmentation: 6 single-GPU jobs spread across 6 nodes, 1 node would fit all", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0017", title: "Job cc1e00a9 over-requested by 6 GPUs, only 2 showed >10% utilization", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0018", title: "Job f26ccb7c held 8 GPUs at 2% mean util — possible data-loading stall", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0019", title: "Queue wait 610min — submit-time analysis shows 24 idle GPUs available", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0020", title: "Job 267314766 idle for 11.4h — checkpoint save may explain gap", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0021", title: "Job 085c68938 held 8 A100s with no GPU kernels launched for 4.8h", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0022", title: "Over-allocation: job requested 8 GPUs, tensor parallelism degree was 2", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0023", title: "Queue wait 558min — 29 running jobs held unused GPUs at submit", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0024", title: "Job e9f9a7d7 held node for 7.2h with zero GPU memory allocated", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0025", title: "Fragmentation: 4 jobs using 1 GPU each on 4 separate 8-GPU nodes", type: "fragmentation", label: "fragmentation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0026", title: "Job be46c7b9 CPU-bound: GPUs at 0% for 3.1h while CPU at 100%", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0027", title: "Queue wait 492min — blocker held 8 GPUs with 0% utilization", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0028", title: "Job 5a312323 over-allocated by 4 GPUs — data parallel batch size too small", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0029", title: "Job b86e52d8 held full 8-GPU node, only 1 GPU utilization >50%", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0030", title: "Queue wait 445min — 21 jobs with unused capacity at submit time", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0031", title: "Job 1e8077af idle for 5.6h — possible NFS mount stall", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0032", title: "Job de2f65ff allocated 8 A100s, model fit on 2 GPUs based on params", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0033", title: "Fragmentation: training job split across 3 nodes due to topology mismatch", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0034", title: "Queue wait 412min — node 2c7d93f7 fully idle while 15 jobs waited", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0035", title: "Job 293f15ad held 8 GPUs with 1% mean SM activity for 6h", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0036", title: "Job 29de149a at 0% SM for entire 12h duration — likely stuck", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0037", title: "Over-allocation: job reserved 8 GPUs, only used pipeline stage on 4", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0038", title: "Queue wait 388min — blocker job held reserved but uncommitted memory", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0039", title: "Job 14ebc79f idle for full 8h slot — dataset preprocessing CPU-only phase", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0040", title: "Job 7a8eca9d held 8 A100s for 9h — GPU util never exceeded 5%", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0041", title: "Fragmentation: eval jobs consuming 1 GPU each on premium 8-GPU nodes", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0042", title: "Queue wait 355min — capacity analysis shows 16 GPUs idle at submit", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0043", title: "Job b8b44bf3 allocated 8 GPUs — tokenizer step ran CPU-only for 4h", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0044", title: "Job 438e420e over-requested 4 GPUs — batch size too small to scale", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0045", title: "Queue wait 330min — blocker job 0451816e held unused GPU reservation", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0046", title: "Job 38e8c73e idle 4.2h — suspected deadlock in multi-process dataloader", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0047", title: "Job 6d4b4e7d at 0% utilization for 3h — MIG partition misconfiguration", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0048", title: "Fragmentation: 8 inference jobs pinned to separate nodes unnecessarily", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0049", title: "Queue wait 298min — 11 idle nodes visible in scheduler at submit time", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0050", title: "Job 22c57f5f held full 8-GPU node, only ran single-GPU eval loop", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0051", title: "Over-allocation: job used --nproc_per_node=8 but model is pipeline-parallel 2", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0052", title: "Queue wait 277min — 8 A100 GPUs idle at blocker node during entire wait", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0053", title: "Job 9ba1f908 held 8 GPUs — environment setup ran 2.8h before any GPU work", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0054", title: "Job c3de36e9 over-allocated by 6 GPUs based on activation memory estimate", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0055", title: "Fragmentation: LLM serving pods spread across 5 nodes, NVLink unused", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0056", title: "Queue wait 254min — preemptible job holding 8 GPUs blocked higher priority", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0057", title: "Job b3582f58 held 8 GPUs — all CUDA kernels finished at hour 2 of 9", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0058", title: "Job 9e21ceca at 3% mean SM for 8h — possible numerical instability loop", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0059", title: "Queue wait 231min — cluster capacity headroom was 24 GPUs at submit", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0060", title: "Job 566f7300 held 8 A100s idle for 7.4h — suspected OOM crash + hang", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0061", title: "Over-allocation: DDP job used 8 ranks but gradient sync stalled at rank 0", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0062", title: "Queue wait 218min — 3 blocker jobs held aggregated 24 idle GPUs", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0063", title: "Job 4acc7772 held 8 GPUs — profiling shows only 1 GPU ever launched kernels", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0064", title: "Fragmentation: mixed GPU type allocation — 4xA100 + 4xV100 on same job", type: "fragmentation", label: "fragmentation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0065", title: "Queue wait 204min — blocker job 77dacead ran eval on 1 of 8 GPUs", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0066", title: "Job 72351da1 idle 5.1h — NCCL init timeout caused by node connectivity issue", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0067", title: "Job 64b5d865 over-allocated by 2 GPUs — grad accum steps made 6 GPUs redundant", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0068", title: "Queue wait 191min — node 4857ee28 had 8 idle GPUs for entire wait period", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0069", title: "Job 9bb271f8 held 8 GPUs — only forward pass, no backward, no optimizer step", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0070", title: "Fragmentation: 4 LoRA fine-tune jobs split across 4 nodes vs possible 1", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0071", title: "Queue wait 178min — 19 idle GPUs at blocker node when job submitted", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0072", title: "Job 431e7651 held 8 A100s — model load took 3.8h, training was 20min", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0073", title: "Job 48e246e5 over-allocated by 6 GPUs — inference batch size was 1", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0074", title: "Queue wait 165min — preemption feasible, policy gap, not hardware constraint", type: "queue_inefficiency", label: "queue", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0075", title: "Job d3b600fc held 8 GPUs at 0% for 4h — distributed deadlock suspected", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0076", title: "Fragmentation: tokenizer preprocessing allocated GPU nodes, ran only CPU", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0077", title: "Queue wait 152min — 32 GPUs idle across cluster at submission timestamp", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0078", title: "Job deda3787 held full node idle 3.2h — inter-node comm setup overhead", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0079", title: "Over-allocation: job used torch.distributed with 1/8 GPUs doing any work", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0080", title: "Queue wait 140min — backfill opportunity missed, scheduler gap identified", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0081", title: "Job 5a68c6a7 held 8 A100s — SM idle 6.1h due to host-device transfer stall", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0082", title: "Fragmentation: 2 jobs each needing 4 GPUs allocated to separate 8-GPU nodes", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0083", title: "Queue wait 127min — node c315a6d1 8 GPUs idle since previous job ended", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0084", title: "Job 2979de57 held 8 GPUs — CUDA stream synchronization bottleneck all GPUs idle", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0085", title: "Job 02391fc6 over-allocated — ZeRO stage 3 with 8 GPUs, model fits in 2", type: "over_allocation", label: "allocation", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0086", title: "Queue wait 115min — 3 blocker jobs combined held 24 idle A100 GPUs", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0087", title: "Job 4e391c00 held 8 GPUs — only 1 GPU used for embedding lookup phase", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0088", title: "Fragmentation: 6 single-step eval jobs spread across cluster, consolidatable", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0089", title: "Queue wait 103min — 40 GPUs idle cluster-wide when job entered queue", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0090", title: "Job a1b7de9c held full node — only 1 GPU used for RLHF reward model scoring", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0091", title: "Over-allocation: inference job allocated 8 GPUs for batch_size=4 request", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0092", title: "Queue wait 91min — preemptible low-priority job held 8 GPUs unnecessarily", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0093", title: "Job 4103dd34 at 2% SM utilization for 7h — gradient explosion, training stalled", type: "idle_allocation", label: "utilization", confidence: "medium", verdict: "REVIEW" },
  { id: "FND-0094", title: "Fragmentation: SFT fine-tune jobs each requesting 1 GPU on 8-GPU reserved nodes", type: "fragmentation", label: "fragmentation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0095", title: "Queue wait 79min — node 9d63c09 idle since prev job; scheduler delay gap", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0096", title: "Job e5035cf6 held 8 A100s — NCCL all-reduce timeout caused 5h idle period", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0097", title: "Over-allocation: job allocated 8 GPUs, activation recompute fit 3 GPUs", type: "over_allocation", label: "allocation", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0098", title: "Queue wait 67min — 5 blocker jobs each holding 8 idle GPUs at submit time", type: "queue_inefficiency", label: "queue", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0099", title: "Job 45535907 held 8 GPUs idle for 2.8h — disk I/O bottleneck pre-training", type: "idle_allocation", label: "utilization", confidence: "high", verdict: "LIKELY_VALID" },
  { id: "FND-0100", title: "Fragmentation: multi-node job crossed rack boundary, 30% higher comm overhead", type: "fragmentation", label: "fragmentation", confidence: "medium", verdict: "REVIEW" },
];

export const reviews = z.array(reviewSchema).parse(reviewsData);

export const labels = [
  { value: "queue", label: "Queue" },
  { value: "utilization", label: "Utilization" },
  { value: "allocation", label: "Allocation" },
  { value: "fragmentation", label: "Fragmentation" },
];

export const types = [
  { value: "idle_allocation", label: "Idle Allocation", icon: ZapOff },
  { value: "queue_inefficiency", label: "Queue Inefficiency", icon: Clock },
  { value: "over_allocation", label: "Over-Allocation", icon: AlertTriangle },
  { value: "fragmentation", label: "Fragmentation", icon: TrendingDown },
];

export const confidences = [
  { label: "High", value: "high", icon: TrendingUp },
  { label: "Medium", value: "medium", icon: Minus },
  { label: "Low", value: "low", icon: TrendingDown },
];
